name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        emacs-version:
          #- 25.3
          #- 26.3
          #- 27.2
          #- 28.2
          #- 29.4
          - 30.1
          - release-snapshot

    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.4'
          architecture: 'x64'

      - uses: actions/cache@v4
        id: cache-cask-packages
        with:
          path: .cask
          key: cache-cask-packages

      - uses: conao3/setup-cask@master

      - run: make
